import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)', // Dark overlay for text contrast
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  layoutWrapper: {
    flex: 1,
    flexDirection: 'row',
  },
  rowDirection: {
    flexDirection: 'row',
  },
  columnDirection: {
    flexDirection: 'column',
  },
  sidebar: {
    width: 260,
    backgroundColor: 'rgba(20, 26, 21, 0.85)',
    borderRightWidth: 1,
    borderRightColor: 'rgba(255, 255, 255, 0.1)',
    paddingVertical: 24,
    paddingHorizontal: 16,
    justifyContent: 'space-between',
  },
  sidebarBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 40,
  },
  smallLogoBox: {
    backgroundColor: '#d9ab55',
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    transform: [{ rotate: '-4deg' }],
  },
  smallLogoText: {
    color: '#111214',
    fontWeight: 'bold',
    fontSize: 16,
  },
  sidebarBrandText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  sidebarMenu: {
    flex: 1,
  },
  sidebarMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  sidebarMenuItemActive: {
    backgroundColor: 'rgba(217, 171, 85, 0.1)',
  },
  menuIcon: {
    marginRight: 12,
    width: 20,
  },
  menuText: {
    color: '#8e929a',
    fontSize: 15,
    fontWeight: '500',
  },
  menuTextActive: {
    color: '#d9ab55',
    fontSize: 15,
    fontWeight: '600',
  },
  badge: {
    marginLeft: 'auto',
    backgroundColor: 'rgba(76, 217, 100, 0.15)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  badgeText: {
    color: '#4cd964',
    fontSize: 11,
    fontWeight: 'bold',
  },
  alertBadge: {
    marginLeft: 'auto',
    backgroundColor: 'rgba(255, 59, 48, 0.15)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  alertBadgeText: {
    color: '#ff3b30',
    fontSize: 11,
    fontWeight: 'bold',
  },
  sidebarFooter: {
    borderTopWidth: 1,
    borderTopColor: '#202227',
    paddingTop: 16,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  logoutText: {
    color: '#ff6b6b',
    fontSize: 15,
    fontWeight: '500',
  },
  mainContent: {
    flex: 1,
    backgroundColor: 'transparent',
    flexDirection: 'column',
  },
  navbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(20, 26, 21, 0.6)',
  },
  navbarGreeting: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  navbarSubtitle: {
    color: '#8e929a',
    fontSize: 13,
    marginTop: 2,
  },
  navbarActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconActionButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#1f2025',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: 10,
    right: 11,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ff3b30',
  },
  logoutIconButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 80,
  },
  weatherBanner: {
    backgroundColor: 'rgba(20, 26, 21, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 24,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 24,
  },
  weatherInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  weatherTemp: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  weatherDetails: {
    color: '#8e929a',
    fontSize: 12,
    marginTop: 4,
  },
  irrigationStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(90, 200, 250, 0.1)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginTop: 10,
  },
  statusDotActive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#5ac8fa',
    marginRight: 6,
  },
  irrigationText: {
    color: '#5ac8fa',
    fontSize: 12,
    fontWeight: '600',
  },
  filtersSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 14,
  },
  sectorChipsRow: {
    paddingVertical: 2,
  },
  sectorChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#1e2025',
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#26282e',
  },
  sectorChipActive: {
    backgroundColor: '#d9ab55',
    borderColor: '#d9ab55',
  },
  sectorChipText: {
    color: '#8e929a',
    fontSize: 14,
    fontWeight: '500',
  },
  sectorChipTextActive: {
    color: '#111214',
    fontWeight: 'bold',
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    flexWrap: 'wrap',
  },
  statsCard: {
    flex: 1,
    minWidth: 150,
    backgroundColor: 'rgba(20, 26, 21, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderLeftWidth: 4,
    borderRadius: 24,
    padding: 16,
    marginRight: 8,
    marginBottom: 8,
  },
  statsCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  statsCardTitle: {
    color: '#8e929a',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 8,
  },
  statsCardVal: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  statsCardSub: {
    color: '#5a5e66',
    fontSize: 11,
  },
  contentSplit: {
    flex: 1,
  },
  contentColumn: {
    backgroundColor: 'rgba(20, 26, 21, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
  },
  columnHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionLink: {
    color: '#d9ab55',
    fontSize: 13,
    fontWeight: '600',
  },
  incidentRow: {
    backgroundColor: '#1b1d22',
    borderWidth: 1,
    borderColor: '#26282e',
    borderRadius: 8,
    padding: 14,
    marginBottom: 12,
  },
  incidentRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  incidentMain: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  priorityDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 10,
  },
  incidentTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
    flex: 1,
  },
  incidentTime: {
    color: '#5a5e66',
    fontSize: 11,
    marginLeft: 10,
  },
  incidentDetailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  incidentType: {
    color: '#8e929a',
    fontSize: 12,
  },
  statusBadge: {
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  statusBadgeCompleted: {
    backgroundColor: 'rgba(76, 217, 100, 0.12)',
  },
  statusBadgeProgress: {
    backgroundColor: 'rgba(90, 200, 250, 0.12)',
  },
  statusBadgePending: {
    backgroundColor: 'rgba(255, 149, 0, 0.12)',
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: 'bold',
  },
  actionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  actionCard: {
    width: '48%',
    backgroundColor: '#1b1d22',
    borderColor: '#26282e',
    borderWidth: 1,
    borderRadius: 10,
    padding: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  actionIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  actionCardTitle: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  mobileTabBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    backgroundColor: 'rgba(20, 26, 21, 0.95)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: Platform.OS === 'ios' ? 12 : 0,
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  tabItemActive: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  tabText: {
    color: '#8e929a',
    fontSize: 10,
    marginTop: 2,
    fontWeight: '500',
  },
  tabTextActive: {
    color: '#d9ab55',
    fontSize: 10,
    marginTop: 2,
    fontWeight: 'bold',
  },
  puCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(0,0,0, 0.5)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    width: '100%',
  },
  puCardSelected: {
    backgroundColor: 'rgba(76, 217, 100, 0.12)',
    borderColor: '#4cd964',
    borderWidth: 1.5,
  },
  puCardContent: {
    flex: 1,
  },
  puCardTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  puCardSubtitle: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 12,
    marginTop: 4,
  },
  loadingContainer: {
    padding: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    color: '#ffffff',
    fontSize: 14,
  },
  errorContainer: {
    padding: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  retryButton: {
    backgroundColor: '#d9ab55',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#111214',
    fontWeight: 'bold',
    fontSize: 14,
  },
});
