export const formStyleBase = {
  container: {
    borderRadius: 20,
    padding: 20,
    paddingBottom: 40,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: '#0007',
  },
  header: {
    marginBottom: 20,
  },
  title: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold' as const,
    marginBottom: 6,
  },
  subtitle: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 13,
    lineHeight: 18,
  },
  inputGroup: {
    marginBottom: 18,
  },
  inputLabel: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 12,
    fontWeight: 'bold' as const,
    marginBottom: 8,
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
  },
  inputWrapper: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    height: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 12,
    paddingHorizontal: 16,
  },
  inputIcon: {
    marginRight: 12,
  },
  inputText: {
    flex: 1,
    color: '#ffffff',
    fontSize: 15,
    height: '100%',
  },
  typeSelectorRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    width: '100%',
    marginBottom: 8,
  },
  originSelectorScroll: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingVertical: 4,
  },
  typeButton: {
    flex: 1,
    height: 46,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 10,
    marginHorizontal: 3,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  typeButtonActive: {
    backgroundColor: 'rgba(217, 171, 85, 0.15)',
    borderColor: '#d9ab55',
  },
  typeButtonText: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 12,
    fontWeight: '600' as const,
  },
  typeButtonTextActive: {
    color: '#d9ab55',
    fontWeight: 'bold' as const,
  },
  inputRowContainer: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    width: '100%',
  },
  buttonRow: {
    flexDirection: 'row' as const,
    marginTop: 10,
    alignItems: 'center' as const,
  },
  cancelButton: {
    paddingHorizontal: 24,
    height: 50,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  cancelButtonText: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 15,
    fontWeight: '600' as const,
  },
  submitButton: {
    backgroundColor: '#d9ab55',
    borderRadius: 12,
    height: 50,
    flexDirection: 'row' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  submitButtonText: {
    color: '#111214',
    fontSize: 15,
    fontWeight: 'bold' as const,
  },
};
